
#PROGRAM-1-TAKE TWO NUMBERS FROM THE USER,AND THEN CALCULATE THEIR SUM AND DISPLAY RESULT.
"""
x=int(input("ENTER FIRST NUMBERS= "))
y=int(input("ENTER SECOND NUMBER= "))
z=x+y
print("SUM OF TWO NUMBERS IS= ",z)

"""
#PROGRAM-2-CALCULATE AREA OF RECTANGLE.LENGTH AND BREADTH SHOULD TAKEN FROM USER
"""
x=int(input("ENTER LENGTH OF RECTANGLE= "))
y=int(input("ENTER BREADTH OF RECTANGLE= "))
z=x*y
print("AREA OF RECTANGLE IS= ",z)


"""
#PROGRAM-3-TO CALCULATE SIMPLE INTREST.NEEDFUL DATA SHOULD BE TAKEN FROM THE USER
"""
p=int(input("ENTER PRINCIPAL VALUE= "))
r=int(input("ENTER RATE= "))
t=int(input("ENTER TIME= "))
x=(p*r*t)/100
print("SIMPLE INTREST IS= ",x)
"""

#PROGRAM-4-CALCULATE AREA OF CIRCLE WHERE RADIUS IS TAKEN FROM THE USER
"""
a=3.14
r=int(input("ENTER  RADIUS OF CIRCLE= "))
y=r*r*a

print("AREA OF CIRCLE IS = ",y)
"""

#PROGRAM-5-TAKE A CHARACTER FROM THE USER AND DISPLAY ITS UNOCODE
"""
y=ord("b")
print(y)

"""

#PROGRAM-6-CONVERT A NUMBER FROM DECIMAL TO BINARY.NUMBER IS TAKEN FROM THE USER
"""
x=int(input("ENTER A DECIMAL NUMBER= "))
y=bin(x)
print("CONVERT DECIMAL TO BINARY= ",y)

"""

#PROGRAM-7-CALCULATE VOLUME OF CUBOID .TAKE DATA FROM THE USER
"""
l=int(input("ENTER LENGTH OF CUBOID= "))
b=int(input("ENTER BREADTH OF CUBOID= "))
h=int(input("ENTER HEIGHT OF CUBOID= "))
x=l*b*h
print("VOLUME OF CUBOID IS= ",x)
"""

#PROGRAM-8-TO FIND THE AVERAGE OF THREE NUMBERS
"""
x=int(input("ENTER FIRST NUMBERS= "))
y=int(input("ENTER SECOND NUMBERS= "))
z=int(input("ENTER THIRD NUMBERS= "))
a=(x+y+z)/3
print("AVERAGE OF THREE NUMBERS IS= ",a)

"""

